steps:
# Build vote
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/microservices-repo/vote', './vote']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/microservices-repo/vote']

# Build result
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/microservices-repo/result', './result']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/microservices-repo/result']

# Build worker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/microservices-repo/worker', './worker']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/microservices-repo/worker']

options:
  logging: CLOUD_LOGGING_ONLY
